var divisionData = {};

divisionData["arc"] = {
    "header": [
        [
            "Team #",
            "Team Name",
            "Events Played",
            "Highest Auto OPR",
            "Highest Coop OPR",
            "Highest OPR (No Coop)"
        ]
    ],
    "data": [
        [
            41,
            "RoboWarriors",
            2,
            0,
            12.16,
            6.67
        ],
        [
            51,
            "The Wings of Fire",
            2,
            0.42,
            9.84,
            31.44
        ],
        [
            68,
            "Truck Town Thunder",
            4,
            0,
            5.2,
            69.09
        ],
        [
            108,
            "SigmaC@T Robotic Team",
            2,
            0,
            0,
            25.41
        ],
        [
            115,
            "MVRT",
            2,
            0,
            6.22,
            18.79
        ],
        [
            122,
            "NASA Knights",
            2,
            0,
            6.64,
            14.99
        ],
        [
            135,
            "Penn Robotics",
            3,
            5.68,
            13.02,
            64.86
        ],
        [
            188,
            "Blizzard",
            2,
            0.1,
            2.55,
            42.54
        ],
        [
            201,
            "The FEDS",
            2,
            0.21,
            4.92,
            15.47
        ],
        [
            207,
            "METALCRAFTERS",
            2,
            0.56,
            2.71,
            23.11
        ],
        [
            217,
            "ThunderChickens",
            4,
            0.11,
            17.76,
            40.63
        ],
        [
            234,
            "Cyber Blue",
            4,
            10.97,
            28.14,
            81.11
        ],
        [
            280,
            "TnT",
            3,
            1.7,
            7.7,
            44.28
        ],
        [
            314,
            "The Megatron Oracles",
            4,
            0,
            8.67,
            80.96
        ],
        [
            360,
            "The Revolution",
            3,
            0.05,
            4.56,
            45.79
        ],
        [
            378,
            "The Circuit Stompers",
            2,
            0,
            11.2,
            20
        ],
        [
            503,
            "Frog Force",
            4,
            0,
            8.54,
            46.41
        ],
        [
            623,
            "Cougar Robotics",
            1,
            0,
            4.44,
            23.97
        ],
        [
            691,
            "Project 691",
            2,
            0.12,
            3.8,
            13.49
        ],
        [
            836,
            "The RoboBees",
            2,
            0.21,
            0,
            36.64
        ],
        [
            857,
            "Superior Roboworks",
            3,
            1.23,
            9.07,
            35.03
        ],
        [
            931,
            "Perpetual Chaos",
            2,
            1.84,
            13.75,
            17.55
        ],
        [
            1023,
            "Bedford Express",
            4,
            14.82,
            14.9,
            109.4
        ],
        [
            1089,
            "Team Mercury",
            3,
            0.68,
            14.95,
            40.92
        ],
        [
            1310,
            "RUNNYMEDE ROBOTICS",
            2,
            8.66,
            16.89,
            47.5
        ],
        [
            1322,
            "Genesee Robotics Area Youth Team (GRAYT)",
            3,
            4.96,
            17.99,
            24.86
        ],
        [
            1538,
            "The Holy Cows",
            2,
            0.05,
            4.6,
            68.01
        ],
        [
            1572,
            "Hammer Heads",
            2,
            0,
            7.89,
            35.27
        ],
        [
            1640,
            "Sab-BOT-age",
            3,
            0,
            4.54,
            79.33
        ],
        [
            1648,
            "G3 Robotics",
            2,
            0,
            7.15,
            23.3
        ],
        [
            1700,
            "Gatorbotics",
            2,
            0.53,
            5.11,
            14.79
        ],
        [
            1701,
            "RoboCubs",
            3,
            0,
            6.02,
            26.53
        ],
        [
            1706,
            "Ratchet Rockers",
            2,
            2.02,
            18.78,
            25.39
        ],
        [
            1714,
            "MORE Robotics",
            2,
            0.41,
            9.55,
            28.32
        ],
        [
            1785,
            "Blue Springs Robocats",
            2,
            1.87,
            10.31,
            19.53
        ],
        [
            2013,
            "Cybergnomes",
            3,
            0,
            3.66,
            37.84
        ],
        [
            2220,
            "Blue Twilight",
            3,
            0.25,
            8.28,
            15.01
        ],
        [
            2338,
            "Gear It Forward",
            2,
            0,
            12.05,
            84.3
        ],
        [
            2342,
            "Team Phoenix",
            3,
            14.6,
            10.91,
            58.57
        ],
        [
            2363,
            "Triple Helix",
            2,
            1.06,
            0,
            57.76
        ],
        [
            2383,
            "Ninjineers",
            3,
            9.69,
            14.53,
            62.32
        ],
        [
            2605,
            "Sehome Seamonsters",
            3,
            0.01,
            6.37,
            44.85
        ],
        [
            2619,
            "The Charge",
            3,
            2.88,
            11.29,
            35.98
        ],
        [
            2655,
            "The Flying Platypi",
            2,
            0.16,
            12.88,
            22.68
        ],
        [
            2848,
            "The All Sparks",
            2,
            0,
            1.21,
            17.47
        ],
        [
            2907,
            "Lion Robotics",
            3,
            0,
            14.92,
            33.6
        ],
        [
            2914,
            "TIGER PRIDE",
            2,
            0.01,
            11.59,
            15.31
        ],
        [
            2974,
            "Walton Robotics",
            2,
            0,
            16.69,
            59.05
        ],
        [
            3103,
            "Iron Plaid",
            2,
            0,
            22.03,
            27.53
        ],
        [
            3238,
            "Cyborg Ferrets",
            3,
            0.18,
            15.89,
            33.47
        ],
        [
            3278,
            "QWERTY Robotics",
            2,
            0.57,
            6.74,
            10.9
        ],
        [
            3284,
            "Camdenton 4H LASER Team",
            2,
            0,
            9.83,
            34.57
        ],
        [
            3322,
            "Eagle Imperium",
            4,
            0.97,
            18.63,
            32.04
        ],
        [
            3357,
            "COMETS",
            2,
            0,
            13.54,
            20.75
        ],
        [
            3602,
            "RoboMos",
            3,
            0.26,
            12.68,
            57.31
        ],
        [
            3996,
            "RIKITIK",
            1,
            0,
            9.54,
            32.09
        ],
        [
            4010,
            "Nautilus",
            2,
            0.46,
            3.27,
            11.74
        ],
        [
            4201,
            "Vitruvian Bots",
            2,
            0,
            3.51,
            58.11
        ],
        [
            4207,
            "PyRobotics",
            1,
            0,
            0,
            11.59
        ],
        [
            4213,
            "MetalCow Robotics",
            3,
            1.44,
            3.98,
            26.91
        ],
        [
            4334,
            "Alberta Tech Alliance (ATA)",
            2,
            0.24,
            10.56,
            26.15
        ],
        [
            4364,
            "Metal Jackets",
            2,
            0.68,
            0.17,
            26.17
        ],
        [
            4451,
            "ROBOTZ Garage",
            2,
            0,
            5.86,
            52.22
        ],
        [
            4977,
            "Iron Lion",
            1,
            0.87,
            2.04,
            21.31
        ],
        [
            5048,
            "Spartronics",
            3,
            1.42,
            3.88,
            76.77
        ],
        [
            5162,
            "The Big Red Theory",
            2,
            0,
            5.02,
            14.78
        ],
        [
            5212,
            "TAMSformers Robotics",
            2,
            0,
            8.86,
            0
        ],
        [
            5403,
            "Aluminosity",
            3,
            0,
            10.35,
            36.87
        ],
        [
            5464,
            "Bluejacket Robotics",
            1,
            0,
            8.07,
            0
        ],
        [
            5505,
            "Wildcat Robotics",
            3,
            3.02,
            22.51,
            29.19
        ],
        [
            5536,
            "TITANS",
            2,
            0,
            7.36,
            7.09
        ],
        [
            5571,
            "RATCHET",
            1,
            0,
            2.91,
            27.59
        ],
        [
            5581,
            "Hornets",
            1,
            0,
            6.68,
            6.41
        ],
        [
            5667,
            "Team AIR",
            2,
            0,
            8.41,
            16.3
        ],
        [
            5687,
            "The Outliers",
            3,
            0,
            8.42,
            22.94
        ],
        [
            5692,
            "ChiefBots",
            3,
            1.43,
            15.4,
            31.16
        ]
    ]
};

divisionData["new"] = {
    "header": [
        [
            "Team #",
            "Team Name",
            "Events Played",
            "Highest Auto OPR",
            "Highest Coop OPR",
            "Highest OPR (No Coop)"
        ]
    ],
    "data": [
        [
            25,
            "Raider Robotix",
            4,
            0,
            13.42,
            43.01
        ],
        [
            74,
            "Team C.H.A.O.S.",
            3,
            0,
            10.55,
            55.96
        ],
        [
            100,
            "The WildHats",
            2,
            0.28,
            8.76,
            13.52
        ],
        [
            118,
            "Robonauts",
            3,
            18.15,
            29.83,
            113.97
        ],
        [
            133,
            "B.E.R.T",
            3,
            0.9,
            17.62,
            36.69
        ],
        [
            155,
            "The Technonuts",
            3,
            3.46,
            19.87,
            41.67
        ],
        [
            175,
            "Buzz Robotics",
            3,
            2.84,
            14.74,
            54.33
        ],
        [
            190,
            "Gompei and the H.E.R.D.",
            3,
            0,
            6.35,
            32.07
        ],
        [
            195,
            "Cyber Knights",
            4,
            0,
            9.08,
            80.2
        ],
        [
            269,
            "CooneyTech",
            1,
            1.21,
            5.88,
            19.49
        ],
        [
            295,
            "Renevatio",
            2,
            0.61,
            8.2,
            21.44
        ],
        [
            321,
            "RoboLancers",
            4,
            0,
            14.67,
            27.02
        ],
        [
            533,
            "The PSIcotics",
            2,
            0.97,
            7.67,
            13.95
        ],
        [
            537,
            "Charger Robotics",
            2,
            1.67,
            3.77,
            23.43
        ],
        [
            540,
            "TALON 540 Godwin Robotics",
            1,
            0,
            6.05,
            19.2
        ],
        [
            587,
            "Hedgehogs",
            2,
            0,
            5.84,
            13.57
        ],
        [
            932,
            "Circuit Chargers",
            2,
            0,
            0,
            23.5
        ],
        [
            955,
            "CV Robotics",
            3,
            0.48,
            3.97,
            68.95
        ],
        [
            1094,
            "Channel Cats",
            1,
            0,
            10.19,
            21.99
        ],
        [
            1111,
            "The Power Hawks",
            2,
            0,
            1,
            18.47
        ],
        [
            1466,
            "Webb Robotics",
            2,
            0.03,
            11.22,
            34.75
        ],
        [
            1671,
            "Buchanan Bird Brains",
            2,
            0,
            5.17,
            93.11
        ],
        [
            1678,
            "Citrus Circuits",
            3,
            15.57,
            14.19,
            93.15
        ],
        [
            1720,
            "PhyXTGears",
            3,
            0,
            3.72,
            54.51
        ],
        [
            1741,
            "Red Alert",
            3,
            2.97,
            9.34,
            38.51
        ],
        [
            1756,
            "Argos",
            2,
            16.24,
            4.14,
            81.51
        ],
        [
            1918,
            "NC GEARS",
            3,
            0,
            8.93,
            62.05
        ],
        [
            1983,
            "Skunk Works Robotics",
            4,
            0,
            6.06,
            83.31
        ],
        [
            2039,
            "Rockford Robotics",
            2,
            0.93,
            1.08,
            28.07
        ],
        [
            2158,
            "ausTIN CANs",
            2,
            0,
            16.11,
            24.26
        ],
        [
            2339,
            "Robolopes",
            2,
            0.33,
            10.66,
            21.03
        ],
        [
            2468,
            "Team Appreciate",
            3,
            0,
            8.98,
            60.45
        ],
		[
            2522,
            "Royal Robotics",
            3,
            0,
            13.24,
            65.37
        ],
        [
            2607,
            "The Fighting RoboVikings",
            3,
            0,
            22.5,
            50.59
        ],
        [
            2761,
            "IronHorse Robotics",
            2,
            0,
            0.13,
            20.18
        ],
        [
            2877,
            "LigerBots",
            3,
            0,
            22.42,
            45.38
        ],
        [
            3015,
            "Ranger Robotics",
            2,
            1.67,
            2.38,
            38.8
        ],
        [
            3039,
            "Wildcat Robotics",
            1,
            1.23,
            6.32,
            28.23
        ],
        [
            3130,
            "The East Ridge Robotic Ominous RaptorS - the ERRORS",
            2,
            0,
            24.72,
            65.96
        ],
        [
            3137,
            "T-Birds",
            1,
            0.38,
            7.86,
            3.92
        ],
        [
            3171,
            "P.R.I.D.E",
            2,
            0.1,
            12.66,
            47.52
        ],
        [
            3310,
            "Black Hawk Robotics",
            3,
            0,
            11.1,
            46.52
        ],
        [
            3314,
            "Mechanical Mustangs",
            5,
            0,
            11.81,
            29.48
        ],
        [
            3464,
            "Sim-City",
            3,
            2.96,
            13.88,
            29.57
        ],
        [
            3467,
            "The Windham Windup",
            3,
            0,
            19.29,
            44.01
        ],
        [
            3539,
            "Byting Bulldogs",
            3,
            1.34,
            10.81,
            44.59
        ],
        [
            3574,
            "HIGH TEKERZ",
            3,
            0.6,
            11.98,
            29.49
        ],
        [
            3641,
            "The Flying Toasters",
            4,
            0.16,
            9.95,
            64.6
        ],
        [
            3783,
            "Robo Wildcats",
            2,
            0,
            2.95,
            8.28
        ],
        [
            3785,
            "Gila Monsters",
            2,
            0,
            0.52,
            16.46
        ],
        [
            3838,
            "Roc City Robotix",
            1,
            1.43,
            14.05,
            22.1
        ],
        [
            3940,
            "CyberTooth",
            3,
            0.64,
            19.22,
            33.26
        ],
        [
            4013,
            "Clockwork Mania",
            2,
            0.01,
            10.95,
            32.17
        ],
        [
            4118,
            "Roaring Riptide",
            1,
            1.28,
            17.03,
            20.93
        ],
        [
            4188,
            "Columbus Space Program",
            2,
            0,
            2.81,
            59.03
        ],
        [
            4322,
            "Clockwork Oranges",
            2,
            0,
            1,
            12.98
        ],
        [
            4471,
            "SPARTRONS",
            2,
            0.49,
            17.87,
            19.71
        ],
        [
            4501,
            "Humans",
            2,
            0.42,
            9.88,
            29.91
        ],
        [
            4522,
            "Team SCREAM",
            3,
            0.04,
            9.77,
            53.28
        ],
        [
            4541,
            "CAV-ineers",
            1,
            0.17,
            4.85,
            5.24
        ],
        [
            4575,
            "The Tin Mints",
            3,
            0,
            8.93,
            22.21
        ],
        [
            4678,
            "CyberCavs",
            2,
            8.5,
            9.73,
            53.99
        ],
        [
            4841,
            "Optimal Robotics",
            2,
            0.08,
            0.07,
            21.04
        ],
        [
            4842,
            "Botrregos",
            2,
            0,
            0,
            7.95
        ],
        [
            4903,
            "Mustangs",
            1,
            2.51,
            4.01,
            18.41
        ],
        [
            4954,
            "4-H Palindrome Robotics",
            3,
            0,
            7.65,
            36.69
        ],
        [
            5012,
            "Gryffingear",
            2,
            0.77,
            0.32,
            12.65
        ],
        [
            5027,
            "Event Horizon",
            1,
            0,
            0,
            3.53
        ],
        [
            5188,
            "Classified Robotics",
            3,
            0,
            5.77,
            51.81
        ],
        [
            5418,
            "The Sonic Screwdrivers",
            1,
            0,
            11.51,
            3.61
        ],
        [
            5479,
            "Cafe Bot",
            1,
            1.4,
            0,
            31.59
        ],
        [
            5489,
            "CSI Golden Eagle Robotics",
            2,
            0.59,
            8.5,
            25.58
        ],
        [
            5495,
            "Aluminati",
            3,
            0.41,
            8.49,
            26.04
        ],
        [
            5511,
            "Cortechs Robotics",
            1,
            0.53,
            12.79,
            19.47
        ],
        [
            5526,
            "tCATs",
            1,
            0,
            0,
            16.96
        ],
        [
            5529,
            "Visalia Vanquishers",
            2,
            0,
            8.59,
            8.49
        ],
        [
            5710,
            "The O-Bots",
            3,
            0,
            17.97,
            27.7
        ]
    ]
};

divisionData["cur"] = {
    "header": [
        [
            "Team #",
            "Team Name",
            "Events Played",
            "Highest Auto OPR",
            "Highest Coop OPR",
            "Highest OPR (No Coop)"
        ]
    ],
    "data": [
        [
            56,
            "R.O.B.B.E.",
            3,
            0,
            9.02,
            57.72
        ],
        [
            57,
            "Leopards",
            2,
            0,
            13.35,
            24.5
        ],
        [
            70,
            "More Martians",
            3,
            8.87,
            10.74,
            56.71
        ],
        [
            88,
            "TJ(Squared)",
            3,
            2.11,
            22.25,
            33.17
        ],
        [
            107,
            "Team R.O.B.O.T.I.C.S.",
            4,
            15.06,
            10.88,
            61.26
        ],
        [
            120,
            "Cleveland's Team",
            3,
            0.3,
            5.84,
            51.52
        ],
        [
            123,
            "Team - Cosmos",
            3,
            2.21,
            22.9,
            30.86
        ],
        [
            148,
            "Robowranglers",
            2,
            17.84,
            8.02,
            96.15
        ],
        [
            176,
            "Aces High",
            4,
            1.46,
            14.99,
            30.99
        ],
        [
            228,
            "GUS Robotics",
            2,
            0.04,
            4.16,
            16.75
        ],
        [
            230,
            "Gaelhawks",
            4,
            10.98,
            17.03,
            44.79
        ],
        [
            271,
            "Mechanical Marauders",
            2,
            1.29,
            9.59,
            36.25
        ],
        [
            303,
            "TEST Team 303",
            4,
            0,
            18.91,
            78.7
        ],
        [
            339,
            "Kilroy Robotics",
            1,
            0.67,
            6.97,
            21.39
        ],
        [
            341,
            "Miss Daisy",
            3,
            0,
            1.69,
            28.15
        ],
        [
            369,
            "High Voltage",
            1,
            0,
            2.33,
            11.7
        ],
        [
            379,
            "RoboCats",
            2,
            0.57,
            1.13,
            75.27
        ],
        [
            610,
            "The Coyotes",
            2,
            0,
            15.83,
            33.32
        ],
        [
            649,
            "M-SET Fish",
            2,
            1.24,
            0,
            23.18
        ],
        [
            701,
            "RoboVikes",
            3,
            0,
            15.2,
            74.99
        ],
        [
            702,
            "Bagel Bytes",
            2,
            0.83,
            4.6,
            4.27
        ],
        [
            708,
            "Hatters Robotics",
            4,
            0,
            18.5,
            19.86
        ],
        [
            842,
            "Falcon Robotics",
            2,
            7.52,
            3.11,
            32.65
        ],
        [
            900,
            "Zebracorns",
            2,
            0.26,
            5.1,
            15.82
        ],
        [
            948,
            "NRG (Newport Robotics Group)",
            3,
            13.95,
            18.45,
            64
        ],
        [
            1086,
            "Blue Cheese",
            2,
            0.2,
            16.91,
            18.76
        ],
        [
            1114,
            "Simbotics",
            3,
            14.58,
            6.83,
            125.24
        ],
        [
            1156,
            "Under Control",
            2,
            0.15,
            7.8,
            50.85
        ],
        [
            1305,
            "Ice Cubed",
            3,
            0.4,
            8.74,
            40.71
        ],
        [
            1318,
            "Issaquah Robotics Society",
            4,
            1.63,
            0,
            65.44
        ],
        [
            1319,
            "Flash",
            2,
            0,
            13.05,
            46.68
        ],
        [
            1506,
            "Metal Muscle",
            3,
            0.03,
            14.11,
            38.49
        ],
        [
            1574,
            "MisCar",
            1,
            0.21,
            8.72,
            48.35
        ],
        [
            1622,
            "Team Spyder",
            3,
            0,
            24.63,
            26.63
        ],
        [
            1816,
            "\"The Green Machine\"",
            2,
            0,
            13.89,
            46.73
        ],
        [
            1923,
            "The MidKnight Inventors",
            4,
            0,
            7,
            39.1
        ],
        [
            2046,
            "Bear Metal",
            3,
            1.75,
            5.05,
            37.04
        ],
        [
            2457,
            "The Law",
            2,
            0,
            2.29,
            48.48
        ],
        [
            2557,
            "SOTAbots",
            4,
            0,
            5.01,
            25.94
        ],
        [
            2594,
            "Naskcorpions",
            1,
            0,
            1.75,
            19.69
        ],
        [
            2994,
            "ASTECHZ",
            2,
            0,
            0.39,
            14.84
        ],
        [
            2996,
            "Cougars Gone Wired",
            2,
            3.74,
            11.64,
            31.45
        ],
        [
            3008,
            "Falcons",
            2,
            0,
            4.19,
            22.77
        ],
        [
            3193,
            "Falco Tech",
            2,
            2.07,
            9.61,
            9.62
        ],
        [
            3309,
            "Friarbots",
            3,
            13.97,
            13.99,
            83.66
        ],
        [
            3452,
            "GreengineerZ",
            3,
            0.3,
            13.03,
            45.44
        ],
        [
            3495,
            "MindCraft",
            2,
            0.96,
            0,
            31.07
        ],
        [
            3663,
            "CPR - Cedar Park Robotics",
            4,
            0,
            3.69,
            64.31
        ],
        [
            3937,
            "Breakaway",
            2,
            0.52,
            2.24,
            46.75
        ],
        [
            3959,
            "Morgan County Mech Tech",
            3,
            0.49,
            9.63,
            46.6
        ],
        [
            3974,
            "E=mCD",
            3,
            2.5,
            10.71,
            26.29
        ],
        [
            4048,
            "Redshift",
            3,
            2.29,
            14.04,
            37.63
        ],
        [
            4061,
            "SciBorgs",
            3,
            0,
            3.59,
            56.89
        ],
        [
            4073,
            "Robo Kats",
            2,
            0,
            1.98,
            23.45
        ],
        [
            4080,
            "Team Reboot",
            1,
            0,
            0,
            0
        ],
        [
            4143,
            "MARS/ WARS",
            2,
            1.25,
            17.17,
            52.56
        ],
        [
            4146,
            "Sabercats",
            2,
            0,
            4.78,
            24.9
        ],
        [
            4355,
            "CP-BOTS",
            1,
            0,
            0,
            17.14
        ],
        [
            4450,
            "Olympia Robotics Federation",
            3,
            0,
            8.37,
            43.77
        ],
        [
            4468,
            "Fernbank LINKS",
            1,
            0,
            0,
            32.05
        ],
        [
            4498,
            "Team X",
            2,
            0,
            13.35,
            17.6
        ],
        [
            4593,
            "Rapid Acceleration",
            1,
            0.44,
            0.42,
            10.24
        ],
        [
            4595,
            "Infinity",
            1,
            0,
            0,
            15.6
        ],
        [
            4613,
            "Barker College - The Red Crusade",
            1,
            0,
            0,
            50.15
        ],
        [
            4653,
            "Ironmen Robotics 4653",
            3,
            0.56,
            13.1,
            26.05
        ],
        [
            4909,
            "Bionics",
            3,
            2.86,
            15.87,
            26.34
        ],
        [
            5046,
            "Jacked Up Jackets",
            3,
            0,
            11.35,
            61.71
        ],
        [
            5407,
            "Wolfpack Robotics",
            3,
            0,
            12.33,
            18.08
        ],
        [
            5472,
            "Stallions",
            2,
            0,
            9.2,
            19.55
        ],
        [
            5572,
            "ROSBOTS",
            2,
            0.27,
            4.71,
            13.6
        ],
        [
            5585,
            "Blood, Sweat & Gears",
            1,
            0,
            7.3,
            13.37
        ],
        [
            5586,
            "Kiel Raiders",
            1,
            1.42,
            0,
            6.29
        ],
        [
            5603,
            "Rise of the Warrior Bots",
            3,
            1.48,
            14.77,
            35.61
        ],
        [
            5654,
            "Phoenix",
            1,
            0,
            0,
            4.72
        ],
        [
            5735,
            "Control Freaks",
            3,
            0.4,
            11.18,
            33.72
        ],
        [
            5737,
            "Mars Style",
            1,
            1.3,
            18.15,
            1.4
        ]
    ]
};

divisionData["gal"] = {
    "header": [
        [
            "Team #",
            "Team Name",
            "Events Played",
            "Highest Auto OPR",
            "Highest Coop OPR",
            "Highest OPR (No Coop)"
        ]
    ],
    "data": [
        [
            1,
            "The Juggernauts",
            3,
            0,
            15.23,
            41.19
        ],
        [
            27,
            "Team RUSH",
            4,
            0.02,
            12.62,
            47.53
        ],
        [
            45,
            "TechnoKats Robotics Team",
            3,
            0,
            15.51,
            27.52
        ],
        [
            102,
            "The Gearheads",
            3,
            0.08,
            4.44,
            14.79
        ],
        [
            111,
            "WildStang",
            2,
            0,
            10.03,
            41.31
        ],
        [
            191,
            "X-CATS",
            1,
            0,
            3.23,
            28.99
        ],
        [
            219,
            "Team Impact",
            4,
            0,
            13.58,
            40.62
        ],
        [
            237,
            "Black Magic Robotics",
            3,
            0,
            18.81,
            22.83
        ],
        [
            245,
            "Adambots",
            3,
            0.2,
            12.07,
            37.81
        ],
        [
            330,
            "The Beach Bots",
            2,
            9.91,
            5.13,
            82.83
        ],
        [
            365,
            "Miracle Workerz",
            3,
            4.02,
            16.98,
            36.79
        ],
        [
            384,
            "Sparky 384",
            1,
            0.19,
            8.25,
            35.19
        ],
        [
            492,
            "Titan Robotics Club",
            3,
            0,
            9.8,
            50.57
        ],
        [
            494,
            "Martians",
            3,
            16.72,
            8.89,
            54.67
        ],
        [
            525,
            "Swartdogs",
            2,
            0,
            6.08,
            78.85
        ],
        [
            568,
            "Nerds of the North",
            1,
            0,
            7.88,
            9.39
        ],
        [
            597,
            "Wolverines",
            3,
            0,
            9.69,
            19.17
        ],
        [
            604,
            "Quixilver",
            2,
            1.14,
            8.93,
            10.21
        ],
        [
            744,
            "Shark Attack",
            2,
            0.98,
            18.89,
            39.48
        ],
        [
            862,
            "Lightning Robotics",
            4,
            0,
            17.08,
            40.11
        ],
        [
            876,
            "Thunder Robotics",
            2,
            0,
            4.29,
            58.18
        ],
        [
            967,
            "Iron Lions",
            2,
            0,
            0.6,
            34.72
        ],
        [
            1002,
            "The CircuitRunners",
            2,
            0,
            10.32,
            14.72
        ],
        [
            1011,
            "CRUSH",
            2,
            0,
            3.05,
            26.91
        ],
        [
            1189,
            "The Gearheads",
            4,
            1.45,
            23.07,
            65.01
        ],
        [
            1477,
            "Texas Torque",
            3,
            0,
            17.3,
            25.79
        ],
        [
            1540,
            "Flaming Chickens",
            3,
            0.1,
            10.63,
            15.92
        ],
        [
            1547,
            "\"Where's Waldo?\"",
            2,
            0,
            9.27,
            6.98
        ],
        [
            1595,
            "Dragons",
            3,
            5.38,
            8.81,
            49.49
        ],
        [
            1619,
            "Up-A-Creek Robotics",
            2,
            0.01,
            16.42,
            73.74
        ],
        [
            1649,
            "The E.M.S. Lakers",
            2,
            2.76,
            27.44,
            9.07
        ],
        [
            1690,
            "Orbit",
            3,
            0,
            6.65,
            90.28
        ],
        [
            1726,
            "N.E.R.D.S. (Nifty Engineering Robotics Design Squad)",
            2,
            0.07,
            6.53,
            30.55
        ],
        [
            1777,
            "Viking Robotics",
            1,
            0,
            15.98,
            3.02
        ],
        [
            1902,
            "Exploding Bacon",
            2,
            1.28,
            5.18,
            27.85
        ],
        [
            2052,
            "KnightKrawler",
            2,
            0,
            1.12,
            47.29
        ],
        [
            2056,
            "OP Robotics",
            3,
            18.26,
            29.1,
            86.58
        ],
        [
            2067,
            "Apple Pi",
            4,
            3.62,
            17.05,
            51.11
        ],
        [
            2168,
            "Aluminum Falcons",
            3,
            0,
            11.95,
            43.09
        ],
        [
            2375,
            "Dragon Robotics",
            3,
            0.29,
            10.74,
            18.2
        ],
        [
            2451,
            "PWNAGE",
            2,
            0.41,
            12.36,
            50.58
        ],
        [
            2502,
            "Talon Robotics",
            2,
            0,
            1.91,
            73.08
        ],
        [
            2626,
            "Evolution",
            1,
            0,
            3.7,
            15.45
        ],
        [
            2836,
            "Team Beta",
            3,
            0,
            14.01,
            45.99
        ],
        [
            2990,
            "Hotwire",
            3,
            0,
            7.07,
            45.55
        ],
        [
            3026,
            "Orange Crush",
            2,
            0.34,
            7.26,
            17.89
        ],
        [
            3142,
            "Aperture",
            3,
            0,
            10.94,
            15.54
        ],
        [
            3146,
            "GRANBY GRUNTS",
            3,
            0.78,
            15.96,
            50.8
        ],
        [
            3175,
            "Knight Vision",
            3,
            0,
            10.01,
            16.14
        ],
        [
            3288,
            "Punchers",
            2,
            0.52,
            4.14,
            31.72
        ],
        [
            3337,
            "Panthrobotics",
            2,
            0.99,
            5.55,
            12.5
        ],
        [
            3397,
            "Robolions",
            1,
            0,
            2.89,
            7.29
        ],
        [
            3410,
            "L.I.F.E.",
            2,
            0,
            2.62,
            15.15
        ],
        [
            3492,
            "P.A.R.T.s",
            1,
            0,
            5.56,
            8.27
        ],
        [
            3562,
            "LiveWire",
            2,
            0.67,
            7.58,
            20.32
        ],
        [
            3618,
            "Petoskey Paladins",
            3,
            2.03,
            15.87,
            43.39
        ],
        [
            3668,
            "TroBots",
            4,
            0.24,
            16.05,
            26.55
        ],
        [
            3674,
            "4-H Clover Bots",
            3,
            0,
            7.56,
            56.72
        ],
        [
            3770,
            "BlitzCreek",
            3,
            0.73,
            11.46,
            17.9
        ],
        [
            3787,
            "Wild Robotocats",
            3,
            0,
            12.03,
            29.97
        ],
        [
            3944,
            "All Knights",
            1,
            0,
            0,
            30.41
        ],
        [
            4198,
            "RoboCats",
            1,
            0.57,
            6.99,
            18.94
        ],
        [
            4373,
            "RooBotics",
            3,
            0.63,
            14,
            26.12
        ],
        [
            4719,
            "Bulldogs",
            1,
            0,
            5.25,
            48.12
        ],
        [
            4920,
            "Belle River Automatons",
            1,
            0.73,
            0,
            4.75
        ],
        [
            4961,
            "Shock and Awe-sum",
            3,
            0,
            2.94,
            37.83
        ],
        [
            5114,
            "Titanium Tigers",
            3,
            0.34,
            6.87,
            35.7
        ],
        [
            5216,
            "E-Ville Empire",
            3,
            0,
            15.87,
            25.57
        ],
        [
            5421,
            "Birch Bots",
            1,
            0,
            0,
            7.68
        ],
        [
            5429,
            "Mountain Lions",
            1,
            0.55,
            2.63,
            20.01
        ],
        [
            5460,
            "Strike Zone",
            3,
            0,
            12.06,
            29.67
        ],
        [
            5498,
            "Wired Devils",
            3,
            0.66,
            0,
            23.35
        ],
        [
            5541,
            "Saber Robotics",
            1,
            0.55,
            4.04,
            9.18
        ],
        [
            5554,
            "The Poros",
            1,
            0.03,
            5.22,
            24.13
        ],
        [
            5584,
            "i c robotics",
            1,
            1.32,
            0.58,
            23.24
        ],
        [
            5725,
            "Yotebot",
            1,
            0,
            2.2,
            10.02
        ]
    ]
};

divisionData["carv"] = {
    "header": [
        [
            "Team #",
            "Team Name",
            "Events Played",
            "Highest Auto OPR",
            "Highest Coop OPR",
            "Highest OPR (No Coop)"
        ]
    ],
    "data": [
        [
            66,
            "The Flyers",
            3,
            2.68,
            6.33,
            56.25
        ],
        [
            71,
            "Team Hammond",
            3,
            1.19,
            19.12,
            51.08
        ],
        [
            75,
            "RoboRaiders",
            3,
            0,
            16.99,
            36.4
        ],
        [
            126,
            "Gael Force",
            3,
            0.8,
            17.67,
            43.1
        ],
        [
            128,
            "The Botcats",
            1,
            0.43,
            4.47,
            6.19
        ],
        [
            144,
            "The R.O.C.K",
            2,
            0.58,
            0,
            28.68
        ],
        [
            172,
            "Northern Force",
            3,
            1.88,
            13.2,
            51.39
        ],
        [
            193,
            "MORT Beta",
            4,
            0,
            15.31,
            62.8
        ],
        [
            216,
            "More RoboDawgs",
            4,
            0.39,
            5.13,
            16.31
        ],
        [
            233,
            "The Pink Team",
            3,
            12.19,
            14.19,
            37.91
        ],
        [
            329,
            "Raiders",
            2,
            18.45,
            23.4,
            44.48
        ],
        [
            337,
            "Hard Working Hard Hats",
            2,
            0,
            9.61,
            9.54
        ],
        [
            359,
            "Hawaiian Kids",
            3,
            0,
            4.17,
            54.58
        ],
        [
            368,
            "Team Kika Mana",
            2,
            6.31,
            14.32,
            71.29
        ],
        [
            585,
            "Cyber Penguins",
            2,
            2.22,
            0,
            13.83
        ],
        [
            771,
            "SWAT",
            2,
            0,
            2.04,
            11.47
        ],
        [
            829,
            "Digital Goats",
            4,
            1.38,
            11.93,
            46.12
        ],
        [
            971,
            "Spartan Robotics",
            2,
            0,
            0,
            63.64
        ],
        [
            1024,
            "Kil-A-Bytes",
            4,
            2.53,
            24.26,
            55.81
        ],
        [
            1208,
            "Metool Brigade",
            2,
            1.06,
            2.32,
            46.77
        ],
        [
            1369,
            "Minotaur",
            2,
            0,
            12.34,
            14.33
        ],
        [
            1425,
            "Error Code Xero",
            3,
            1.4,
            7.4,
            45.71
        ],
        [
            1592,
            "Bionic Tigers",
            3,
            10.85,
            3.47,
            55.71
        ],
        [
            1625,
            "Winnovation",
            2,
            0,
            3.86,
            51.11
        ],
        [
            1717,
            "D'Penguineers",
            2,
            7.99,
            5.88,
            48.25
        ],
        [
            1718,
            "The Fighting Pi",
            3,
            2.71,
            13.8,
            27.49
        ],
        [
            1768,
            "Robo Chiefs",
            3,
            0.16,
            16.76,
            63.8
        ],
        [
            1868,
            "Space Cookies",
            2,
            0.08,
            1.25,
            30.68
        ],
        [
            1884,
            "Griffins",
            1,
            0.49,
            2.94,
            19.63
        ],
        [
            1986,
            "Team Titanium",
            3,
            9.08,
            19.97,
            74.16
        ],
        [
            2130,
            "Alpha+",
            1,
            0.7,
            6.3,
            24.55
        ],
        [
            2337,
            "EngiNERDs",
            3,
            0,
            11.58,
            39.77
        ],
        [
            2491,
            "No Mythic",
            2,
            0,
            5.54,
            3.52
        ],
        [
            2630,
            "Thunderbolts",
            2,
            0,
            5.77,
            29
        ],
        [
            2648,
            "Infinite Loop",
            3,
            0.76,
            20.16,
            17.13
        ],
        [
            2767,
            "Stryke Force",
            3,
            0,
            3.91,
            52.01
        ],
        [
            2834,
            "Bionic Black Hawks",
            3,
            0,
            15.5,
            44.52
        ],
        [
            2852,
            "DM High Voltage",
            3,
            0,
            5.28,
            66.14
        ],
        [
            2876,
            "Devilbotz",
            3,
            0.44,
            16.53,
            19.03
        ],
        [
            3140,
            "Flagship",
            2,
            0.93,
            17.85,
            44.96
        ],
        [
            3324,
            "The Metrobots",
            2,
            0.06,
            2.78,
            12.29
        ],
        [
            3352,
            "Flaming Monkeys 4-H Robotics Club",
            2,
            0.99,
            3.69,
            17.48
        ],
        [
            3419,
            "RoHawks",
            2,
            0,
            12.76,
            64.71
        ],
        [
            3504,
            "Girls of Steel",
            2,
            0.8,
            12.63,
            8.5
        ],
        [
            3507,
            "Ubotics",
            2,
            0,
            3.35,
            13.15
        ],
        [
            3512,
            "Spartatroniks",
            2,
            0,
            6.28,
            51.53
        ],
        [
            3536,
            "Electro Eagles",
            3,
            1.9,
            15.36,
            44.94
        ],
        [
            3566,
            "Gone Fishin'",
            2,
            2.35,
            8.72,
            26.5
        ],
        [
            3653,
            "BotCats",
            3,
            0.74,
            14.05,
            24.32
        ],
        [
            3721,
            "Charger Robotics",
            1,
            0,
            4.38,
            17.83
        ],
        [
            3802,
            "RoboPOP",
            1,
            0,
            8.52,
            12.35
        ],
        [
            3844,
            "Kentucky Wildbots",
            1,
            0,
            9.78,
            12.01
        ],
        [
            3881,
            "WHEA Sharkbots",
            2,
            0.44,
            7.67,
            8.57
        ],
        [
            4001,
            "Retro-Rams",
            2,
            0,
            3.6,
            57.19
        ],
        [
            4039,
            "MakeShift Robotics",
            2,
            0,
            5.07,
            56.35
        ],
        [
            4183,
            "Bit Buckets",
            2,
            0,
            3.58,
            35.06
        ],
        [
            4253,
            "TAS Robotics",
            2,
            0.88,
            0,
            50.28
        ],
        [
            4381,
            "Twisted Devils",
            4,
            0,
            23.76,
            36.95
        ],
        [
            4384,
            "Benzene Bots",
            3,
            0.95,
            8.2,
            38.01
        ],
        [
            4536,
            "MinuteBots",
            1,
            0,
            3.28,
            14.25
        ],
        [
            4721,
            "Tiger Bots",
            2,
            0.27,
            0,
            6.57
        ],
        [
            4911,
            "CyberKnights",
            4,
            0,
            9.86,
            42
        ],
        [
            4915,
            "Spartronics",
            3,
            0,
            23.77,
            35.39
        ],
        [
            4945,
            "Titanium-Wrecks",
            1,
            0,
            0,
            0
        ],
        [
            4967,
            "That ONE Team - Our Next Engineers",
            3,
            14.22,
            21.26,
            52.78
        ],
        [
            5260,
            "Owosso Operating System",
            3,
            0,
            11.31,
            34.33
        ],
        [
            5291,
            "Emperius",
            1,
            2.32,
            6.86,
            17.59
        ],
        [
            5402,
            "Iron Kings",
            3,
            0.11,
            12.33,
            35.64
        ],
        [
            5431,
            "Titan Robotics",
            1,
            0.41,
            6.96,
            19
        ],
        [
            5437,
            "Rocky Balboabots",
            1,
            1.33,
            7.82,
            16.75
        ],
        [
            5442,
            "Mechanical Monarchy",
            1,
            0,
            0.38,
            26.97
        ],
        [
            5458,
            "Digital Minds",
            1,
            0.14,
            0,
            4.88
        ],
        [
            5465,
            "BinaryBots",
            1,
            0,
            1.64,
            9.43
        ],
        [
            5515,
            "Blue Power Robotics",
            1,
            0,
            2.87,
            16.32
        ],
        [
            5546,
            "A.R.T.",
            1,
            0,
            0.68,
            0
        ],
        [
            5689,
            "CK Cyber Pack",
            1,
            1.55,
            0,
            8.66
        ]
    ]
};

divisionData["hop"] = {
    "header": [
        [
            "Team #",
            "Team Name",
            "Events Played",
            "Highest Auto OPR",
            "Highest Coop OPR",
            "Highest OPR (No Coop)"
        ]
    ],
    "data": [
        [
            11,
            "MORT",
            5,
            0,
            9.81,
            46.36
        ],
        [
            33,
            "Killer Bees",
            3,
            6.04,
            10.76,
            89.38
        ],
        [
            78,
            "AIR Strike",
            2,
            0,
            20.6,
            28.63
        ],
        [
            103,
            "Cybersonics",
            3,
            1.58,
            11.51,
            32.08
        ],
        [
            125,
            "NUTRONS",
            5,
            0,
            16.66,
            52.92
        ],
        [
            166,
            "Chop Shop",
            3,
            2.8,
            13.96,
            32.72
        ],
        [
            223,
            "Xtreme Heat",
            3,
            0,
            9.57,
            15.91
        ],
        [
            263,
            "Sachem Aftershock",
            3,
            0.78,
            7.59,
            66.13
        ],
        [
            343,
            "Metal-In-Motion",
            2,
            0.59,
            11.04,
            48.05
        ],
        [
            469,
            "Las Guerrillas",
            4,
            0.18,
            10.12,
            66.79
        ],
        [
            548,
            "Robostangs",
            4,
            1.36,
            15.41,
            74.52
        ],
        [
            573,
            "Mech Warriors",
            3,
            0.12,
            21.4,
            51.1
        ],
        [
            781,
            "Kinetic Knights",
            2,
            1.32,
            1.94,
            15.87
        ],
        [
            811,
            "Cardinals",
            3,
            1.99,
            9.82,
            29.74
        ],
        [
            987,
            "HIGHROLLERS",
            2,
            2.36,
            13.3,
            71.56
        ],
        [
            1124,
            "ÃœberBots",
            4,
            0,
            10.19,
            38.3
        ],
        [
            1218,
            "Vulcan Robotics",
            4,
            1.31,
            11.51,
            63.09
        ],
        [
            1391,
            "The METAL MOOSE",
            2,
            0,
            7.64,
            9.05
        ],
        [
            1533,
            "Triple Strange",
            2,
            0.6,
            12.12,
            10.17
        ],
        [
            1676,
            "The Pascack PI-oneers",
            4,
            0.2,
            15.58,
            56.63
        ],
        [
            1723,
            "The FBI - FIRST Bots of Independence",
            2,
            0,
            2.32,
            37.57
        ],
        [
            1746,
            "Team OTTO",
            2,
            0,
            15.36,
            32.22
        ],
        [
            1796,
            "RoboTigers",
            2,
            0.24,
            9.29,
            28.46
        ],
        [
            1817,
            "Llano Estacado RoboRaiders",
            2,
            0,
            10.13,
            31.79
        ],
        [
            2016,
            "Mighty Monkey Wrenches",
            3,
            0,
            15.96,
            56.1
        ],
        [
            2064,
            "The Panther Project",
            3,
            3.45,
            14.5,
            28.51
        ],
        [
            2169,
            "KING TeC",
            2,
            0,
            16.23,
            45.14
        ],
        [
            2183,
            "Tigerbots",
            1,
            0,
            11.74,
            9.86
        ],
        [
            2228,
            "CougarTech",
            2,
            0,
            5.99,
            46.98
        ],
        [
            2344,
            "The Saunders Droid Factory",
            1,
            0.06,
            0,
            34.96
        ],
        [
            2500,
            "Herobotics",
            2,
            0.76,
            6.53,
            5.72
        ],
        [
            2512,
            "Duluth East Daredevils",
            2,
            17.82,
            21.31,
            43
        ],
        [
            2530,
            "Inconceivable",
            1,
            0.21,
            0,
            14.42
        ],
        [
            2531,
            "RoboHawks",
            2,
            1.08,
            17.63,
            13.83
        ],
        [
            2590,
            "Nemesis",
            4,
            1.88,
            9.98,
            69.63
        ],
        [
            2609,
            "BeaverworX",
            2,
            0,
            9.25,
            25.26
        ],
        [
            2614,
            "MARS",
            2,
            0,
            10.13,
            58.48
        ],
        [
            2783,
            "Engineers of Tomorrow",
            2,
            3.73,
            14.92,
            36.92
        ],
        [
            2826,
            "Wave Robotics",
            2,
            27.33,
            2.86,
            115.34
        ],
        [
            2830,
            "Riverside RoboTigers",
            2,
            0,
            9.54,
            27.02
        ],
        [
            3042,
            "Cobalt Catalysts",
            2,
            0,
            5.83,
            27.04
        ],
        [
            3098,
            "The Captains",
            3,
            6.8,
            12.15,
            36.42
        ],
        [
            3255,
            "Super NURDs",
            2,
            0.32,
            0.89,
            50.48
        ],
        [
            3266,
            "Robots-R-Us",
            2,
            2.7,
            9.24,
            18.7
        ],
        [
            3501,
            "Firebots",
            2,
            1.9,
            14.7,
            17.51
        ],
        [
            3620,
            "Average Joes",
            3,
            0,
            15,
            50.2
        ],
        [
            3683,
            "Team Dave",
            2,
            7.78,
            17.5,
            65.87
        ],
        [
            3688,
            "Norsemen",
            3,
            0.7,
            20.53,
            35.86
        ],
        [
            3735,
            "Klein Bots",
            3,
            0,
            5.02,
            48.47
        ],
        [
            3939,
            "Robotic Knights",
            1,
            0,
            0,
            16.88
        ],
        [
            3950,
            "Robo Gym",
            1,
            0,
            2.59,
            30.5
        ],
        [
            4130,
            "The Blue Devils",
            3,
            1.99,
            13.09,
            40.98
        ],
        [
            4265,
            "Secret City Wildbots",
            2,
            0.1,
            13.21,
            20.88
        ],
        [
            4329,
            "Lutheran Roboteers",
            2,
            0,
            15.27,
            9.22
        ],
        [
            4362,
            "Gems",
            3,
            1.33,
            17.16,
            60.09
        ],
        [
            4391,
            "BraveBots",
            3,
            0.74,
            14.47,
            45.17
        ],
        [
            4405,
            "The Atoms Family",
            3,
            3.42,
            12.93,
            21.21
        ],
        [
            4486,
            "Blue Prints",
            1,
            0.02,
            1.82,
            12.37
        ],
        [
            4550,
            "Something's Bruin",
            2,
            0.2,
            14.93,
            32.19
        ],
        [
            4589,
            "AdamasBots",
            1,
            0,
            0,
            0.73
        ],
        [
            4731,
            "MONARCH-E",
            2,
            0,
            6.6,
            11.62
        ],
        [
            4799,
            "Lazbuddie Robotics sponsored by Society of Women Engineers",
            1,
            0.05,
            1.94,
            4.64
        ],
        [
            4918,
            "The Roboctopi",
            3,
            0,
            2.24,
            44.99
        ],
        [
            4930,
            "The Electric Mayhem",
            2,
            0,
            1.87,
            21.67
        ],
        [
            5015,
            "SWAT Bots Robotics",
            1,
            0.46,
            7.49,
            24.28
        ],
        [
            5024,
            "Raider Robotics",
            1,
            0,
            4.23,
            22.12
        ],
        [
            5118,
            "KHS",
            1,
            0,
            0,
            11.89
        ],
        [
            5318,
            "DigiDigger",
            1,
            0.89,
            2.45,
            18.65
        ],
        [
            5413,
            "Stellar Robotics",
            2,
            0.35,
            3.69,
            44.26
        ],
        [
            5428,
            "Breaking Bots",
            1,
            0.06,
            2.67,
            15.76
        ],
        [
            5454,
            "Wild Fire",
            2,
            0,
            6.46,
            20.49
        ],
        [
            5493,
            "SMAbotics AG",
            1,
            0.73,
            1.07,
            10.85
        ],
        [
            5509,
            "Like a Boss.",
            3,
            0.11,
            12.21,
            32.4
        ],
        [
            5562,
            "Lakers",
            3,
            0.42,
            9.43,
            37.49
        ],
        [
            5576,
            "Team Terminator",
            1,
            0.2,
            7.23,
            39.18
        ],
        [
            5771,
            "Marfa Robohorns",
            1,
            0,
            5.69,
            14.91
        ]
    ]
};

divisionData["tes"] = {
    "header": [
        [
            "Team #",
            "Team Name",
            "Events Played",
            "Highest Auto OPR",
            "Highest Coop OPR",
            "Highest OPR (No Coop)"
        ]
    ],
    "data": [
        [
            48,
            "Delphi E.L.I.T.E.",
            3,
            0.39,
            6.26,
            65.84
        ],
        [
            58,
            "The Riot Crew",
            3,
            0,
            14.3,
            43.31
        ],
        [
            141,
            "WOBOT",
            4,
            0,
            23.41,
            32
        ],
        [
            171,
            "Cheese Curd Herd",
            2,
            0,
            22.04,
            14.14
        ],
        [
            226,
            "Hammerheads",
            3,
            0,
            18.46,
            51.15
        ],
        [
            244,
            "RoboDawgs 3D",
            4,
            1.11,
            4.63,
            19.48
        ],
        [
            292,
            "PantherTech",
            3,
            0.15,
            15.22,
            28.11
        ],
        [
            319,
            "Big Bad Bob",
            3,
            10.33,
            3.83,
            49.14
        ],
        [
            340,
            "G.R.R. (Greater Rochester Robotics)",
            2,
            1.27,
            6.35,
            40.32
        ],
        [
            358,
            "Robotic Eagles",
            2,
            0.25,
            14.65,
            16.05
        ],
        [
            612,
            "Chantilly Robotics",
            2,
            0.54,
            5.68,
            17.06
        ],
        [
            624,
            "CRyptonite",
            3,
            18.06,
            24.32,
            81.84
        ],
        [
            668,
            "The Apes of Wrath",
            2,
            0.49,
            3.66,
            24.39
        ],
        [
            706,
            "CYBERHAWKS",
            2,
            0.89,
            6.33,
            40.95
        ],
        [
            1025,
            "IMPIS",
            3,
            1.41,
            9.15,
            47.45
        ],
        [
            1225,
            "Gorillas",
            2,
            0,
            7.21,
            26.28
        ],
        [
            1255,
            "Blarglefish",
            2,
            0.67,
            0,
            28.32
        ],
        [
            1311,
            "Kell Robotics",
            2,
            0.36,
            7.15,
            21.26
        ],
        [
            1323,
            "MadTown Robotics",
            2,
            1.36,
            6.94,
            6.45
        ],
        [
            1403,
            "Cougar Robotics",
            3,
            0,
            8.72,
            61.84
        ],
        [
            1502,
            "Technical Difficulties",
            3,
            0.98,
            10.82,
            48.31
        ],
        [
            1515,
            "MorTorq",
            2,
            0.69,
            10.21,
            18.72
        ],
        [
            1523,
            "Mega Awesome Robotic Systems (MARS)",
            2,
            0,
            6.3,
            60.57
        ],
        [
            1610,
            "B.O.T. (Builders of Tomorrow)",
            2,
            0.75,
            4.33,
            11.58
        ],
        [
            1647,
            "Iron Devils",
            3,
            1.5,
            13.63,
            41.88
        ],
        [
            1658,
            "Tech Heads",
            1,
            0,
            5,
            70.36
        ],
        [
            1806,
            "S.W.A.T.",
            2,
            0.08,
            4.05,
            98.15
        ],
        [
            1836,
            "The MilkenKnights",
            3,
            0,
            7.27,
            30.04
        ],
        [
            2054,
            "Tech Vikes",
            4,
            13.41,
            10.13,
            60.95
        ],
        [
            2059,
            "The Hitchhikers",
            2,
            0,
            0.87,
            15.78
        ],
        [
            2062,
            "C.O.R.E 2062",
            2,
            0.49,
            8.52,
            58.53
        ],
        [
            2122,
            "Team Tators",
            2,
            0,
            3.33,
            98.3
        ],
        [
            2137,
            "TORC",
            4,
            0.61,
            5.12,
            73.5
        ],
        [
            2170,
            "Titanium Tomahawks",
            3,
            0,
            9.25,
            61.06
        ],
        [
            2191,
            "Flux Core",
            3,
            0,
            15.21,
            26.4
        ],
        [
            2399,
            "Fighting Unicorns",
            2,
            0.89,
            10.54,
            12.55
        ],
        [
            2415,
            "WiredCats",
            2,
            0,
            9.66,
            29.65
        ],
        [
            2481,
            "Roboteers",
            2,
            14.64,
            24.07,
            73.84
        ],
        [
            2486,
            "CocoNuts",
            2,
            0.25,
            10.21,
            9.02
        ],
        [
            2526,
            "Crimson Robotics",
            2,
            0,
            19.24,
            25.3
        ],
        [
            2587,
            "DiscoBots",
            2,
            0.11,
            33.62,
            42.51
        ],
        [
            2613,
            "PROTOBOT",
            1,
            0,
            0,
            0.16
        ],
        [
            2635,
            "Lake Monsters",
            3,
            0,
            12.74,
            41.76
        ],
        [
            2658,
            "Team Pedestrian",
            1,
            0.03,
            2.07,
            20.48
        ],
        [
            2875,
            "CyberHawks",
            1,
            0.16,
            0,
            26.67
        ],
        [
            2883,
            "F.R.E.D (Fighting Rednecks Engineering and Design)",
            2,
            0,
            7.96,
            54.67
        ],
        [
            2930,
            "Glacier Peak Sonic Squirrels",
            4,
            1,
            6.93,
            50.95
        ],
        [
            2950,
            "Devastators",
            2,
            0,
            2.54,
            13.72
        ],
        [
            2959,
            "Robotarians",
            4,
            2.09,
            20.54,
            53.6
        ],
        [
            2960,
            "automation nation",
            4,
            0,
            19.86,
            41.21
        ],
        [
            2992,
            "The SS Prometheus",
            1,
            1.06,
            6.84,
            4.17
        ],
        [
            3132,
            "Thunder Down Under",
            2,
            11.83,
            4.04,
            61.49
        ],
        [
            3184,
            "Blaze Robotics",
            2,
            0,
            9.77,
            4.71
        ],
        [
            3250,
            "Kennedy Robotics",
            2,
            4.81,
            9.8,
            30.49
        ],
        [
            3360,
            "Hyperion",
            2,
            9.94,
            0,
            61.11
        ],
        [
            3476,
            "Code Orange",
            2,
            0,
            1.53,
            69.61
        ],
        [
            3656,
            "Dreadbots",
            3,
            0,
            15.31,
            24.5
        ],
        [
            3824,
            "HVA RoHAWKtics",
            2,
            0.04,
            8.92,
            91.06
        ],
        [
            3847,
            "Spectrum",
            2,
            0,
            13.85,
            8.05
        ],
        [
            3941,
            "Absolute Zero Electricity (AZE)",
            2,
            1.32,
            12.9,
            11.18
        ],
        [
            4003,
            "TriSonics",
            3,
            7.33,
            12.76,
            40.87
        ],
        [
            4050,
            "4-H Biohazard",
            2,
            0.26,
            0,
            11.1
        ],
        [
            4256,
            "Cyborg Cats",
            2,
            0.9,
            16.08,
            41.68
        ],
        [
            4481,
            "Team Rembrandts",
            1,
            0,
            15.14,
            20.88
        ],
        [
            4571,
            "Rambots",
            1,
            0.28,
            6.97,
            1.3
        ],
        [
            5006,
            "Apophis",
            2,
            0.94,
            7.78,
            19.09
        ],
        [
            5072,
            "Raider Robotics",
            3,
            0,
            7.25,
            26.66
        ],
        [
            5314,
            "ICE BOTS",
            2,
            1.82,
            12.31,
            27.86
        ],
        [
            5415,
            "Bears",
            2,
            0,
            6.77,
            37.7
        ],
        [
            5422,
            "Stormgears FRC",
            2,
            0.84,
            0,
            6.35
        ],
        [
            5528,
            "Ultime",
            1,
            0,
            2.33,
            15.2
        ],
        [
            5582,
            "Rex Machina",
            1,
            0.24,
            0,
            6.32
        ],
        [
            5627,
            "Ï€rates (Pi-rates)",
            1,
            0,
            0.84,
            11.95
        ],
        [
            5678,
            "Knightrise",
            1,
            0,
            3.72,
            4.92
        ],
        [
            5712,
            "Gray Matter",
            4,
            0,
            8.8,
            23.14
        ],
        [
            5730,
            "The Professionals",
            1,
            1.14,
            0,
            7.62
        ]
    ]
};

divisionData["cars"] = {
    "header": [
        [
            "Team #",
            "Team Name",
            "Events Played",
            "Highest Auto OPR",
            "Highest Coop OPR",
            "Highest OPR (No Coop)"
        ]
    ],
    "data": [
        [
            16,
            "Bomb Squad",
            2,
            1.66,
            0,
            66.07
        ],
        [
            20,
            "The Rocketeers",
            2,
            1.07,
            11.53,
            24.7
        ],
        [
            60,
            "Bionic Bulldogs",
            2,
            0.48,
            2.69,
            71.52
        ],
        [
            67,
            "The HOT Team",
            3,
            17.19,
            7,
            86.71
        ],
        [
            85,
            "B.O.B. (Built on Brains)",
            3,
            0,
            15.27,
            54.73
        ],
        [
            93,
            "FIRST Robotics Team 93: NEW Apple Corps",
            2,
            0,
            10.81,
            24.63
        ],
        [
            173,
            "R.A.G.E. (Robotics & Gadget Engineering)",
            3,
            3.22,
            5.94,
            35.48
        ],
        [
            203,
            "One TUFF Team (Team United for FIRST)",
            3,
            0.76,
            17.67,
            40.44
        ],
        [
            225,
            "TechFire",
            3,
            12.36,
            18.3,
            77.29
        ],
        [
            236,
            "Techno-Ticks",
            3,
            8.87,
            4.41,
            39.75
        ],
        [
            246,
            "Overclocked",
            4,
            6.6,
            10.12,
            48.97
        ],
        [
            254,
            "The Cheesy Poofs",
            2,
            17.57,
            18.93,
            137.32
        ],
        [
            375,
            "Robotic Plague",
            2,
            0,
            1.9,
            24.7
        ],
        [
            399,
            "Eagle Robotics",
            3,
            0,
            8.2,
            64.56
        ],
        [
            418,
            "Purple Haze",
            2,
            0.11,
            4.41,
            42.67
        ],
        [
            467,
            "Shrewsbury Colonials",
            3,
            0,
            7.33,
            24.43
        ],
        [
            558,
            "Robo Squad",
            4,
            1.07,
            13.17,
            33.88
        ],
        [
            973,
            "Greybots",
            2,
            1.07,
            1.17,
            61.71
        ],
        [
            999,
            "MechaRams",
            3,
            0,
            14.74,
            52.33
        ],
        [
            1058,
            "PVC Pirates",
            3,
            0,
            12.46,
            32.24
        ],
        [
            1241,
            "THEORY6",
            3,
            0.07,
            6.25,
            24.14
        ],
        [
            1296,
            "Full Metal Jackets",
            3,
            0,
            6.04,
            70.33
        ],
        [
            1306,
            "BadgerBOTS",
            1,
            0,
            0,
            10.04
        ],
        [
            1325,
            "Inverse Paradox",
            3,
            0,
            6.48,
            62.36
        ],
        [
            1458,
            "Red Tie Robotics",
            2,
            0,
            13.67,
            22.11
        ],
        [
            1501,
            "Team THRUST",
            4,
            0,
            16.29,
            54.54
        ],
        [
            1510,
            "Wildcats",
            4,
            0,
            6.09,
            41.05
        ],
        [
            1511,
            "Rolling Thunder",
            2,
            0,
            9.9,
            37.54
        ],
        [
            1519,
            "Mechanical Mayhem",
            4,
            15.82,
            27.25,
            83.4
        ],
        [
            1629,
            "Garrett Coalition (GaCo)",
            2,
            8.83,
            19.28,
            27.12
        ],
        [
            1710,
            "The Ravonics Revolution",
            1,
            0.3,
            0,
            10.77
        ],
        [
            1711,
            "Raptors",
            3,
            0.74,
            8.13,
            42.55
        ],
        [
            1730,
            "Team Driven",
            2,
            15.54,
            13.69,
            83.24
        ],
        [
            1885,
            "ILITE Robotics",
            2,
            0,
            12.94,
            20.04
        ],
        [
            2075,
            "Enigma Robotics",
            3,
            6.65,
            10.85,
            20.34
        ],
        [
            2085,
            "RoboDogs",
            2,
            2.04,
            11.7,
            91.01
        ],
        [
            2283,
            "Panteras",
            1,
            0.49,
            0.1,
            16.41
        ],
        [
            2377,
            "C Company",
            2,
            0,
            3.65,
            34.74
        ],
        [
            2471,
            "Team Mean Machine",
            3,
            0,
            16.74,
            59.74
        ],
        [
            2521,
            "SERT",
            3,
            0.1,
            13.08,
            34.61
        ],
        [
            2534,
            "The Lakers",
            2,
            0,
            2.12,
            31.89
        ],
        [
            2601,
            "Steel Hawks",
            2,
            0.82,
            4.63,
            33.46
        ],
        [
            2905,
            "Sultans of Turkiye",
            1,
            0.08,
            1.71,
            8.42
        ],
        [
            3256,
            "WarriorBorgs",
            2,
            0.26,
            8.59,
            23.21
        ],
        [
            3339,
            "BumbleB",
            1,
            0.27,
            7.42,
            49.49
        ],
        [
            3478,
            "LamBot",
            2,
            0,
            19.99,
            55.51
        ],
        [
            3481,
            "Bronc Botz",
            3,
            0,
            21.17,
            31.23
        ],
        [
            3506,
            "YETI Robotics",
            2,
            0,
            0,
            33.97
        ],
        [
            3547,
            "Virus",
            4,
            2.32,
            21.49,
            35.92
        ],
        [
            3604,
            "Goon Squad",
            3,
            0.72,
            15.86,
            48.78
        ],
        [
            3728,
            "Iron Panda",
            1,
            0,
            12.49,
            0
        ],
        [
            3880,
            "Kealakehe Tiki Techs",
            2,
            0.89,
            10.57,
            4.66
        ],
        [
            3946,
            "Tiger Robotics",
            1,
            0,
            5.74,
            4.01
        ],
        [
            4028,
            "The Beak Squad",
            2,
            0,
            6.88,
            37.83
        ],
        [
            4215,
            "Tritons",
            1,
            0,
            13.57,
            10.16
        ],
        [
            4488,
            "Shockwave",
            3,
            0.86,
            1,
            90.55
        ],
        [
            4499,
            "The Highlanders",
            2,
            0,
            15.7,
            33.58
        ],
        [
            4574,
            "Average Joe's",
            2,
            0,
            0,
            11.6
        ],
        [
            4587,
            "Jersey Voltage",
            2,
            0.57,
            13.86,
            58.69
        ],
        [
            4818,
            "The Herd",
            2,
            0,
            0,
            11.1
        ],
        [
            4953,
            "TBA",
            1,
            0,
            0,
            3.88
        ],
        [
            4980,
            "Canine Crusaders",
            4,
            0,
            16.77,
            39.26
        ],
        [
            5053,
            "Lakers",
            3,
            0,
            15.59,
            36.12
        ],
        [
            5059,
            "TigeRobotics",
            1,
            0,
            0,
            5.45
        ],
        [
            5122,
            "robOTies",
            3,
            0.22,
            14.81,
            47.21
        ],
        [
            5254,
            "Robot Raiders",
            2,
            0.81,
            11.15,
            71.18
        ],
        [
            5338,
            "RoboLoCo",
            2,
            0,
            6.88,
            40.29
        ],
        [
            5406,
            "Celt-X",
            1,
            0.26,
            19.6,
            56.33
        ],
        [
            5416,
            "TaRDIS",
            2,
            0.32,
            7.25,
            20.57
        ],
        [
            5510,
            "The Da Vinci Coders",
            1,
            0,
            0.21,
            2.98
        ],
        [
            5549,
            "Gryphons.exe",
            1,
            0.57,
            11.29,
            16.65
        ],
        [
            5625,
            "TrojanBots",
            1,
            0,
            2.12,
            15.18
        ],
        [
            5655,
            "Cryptex",
            1,
            0,
            4.6,
            1.08
        ],
        [
            5659,
            "Team Supreme",
            1,
            0.73,
            9.36,
            29.53
        ],
        [
            5696,
            "Faraday",
            1,
            0,
            1.53,
            5.06
        ],
        [
            5719,
            "Titans",
            2,
            1.92,
            6.34,
            12.15
        ]
    ]
};